### PR TITLE
Edited README.md

### LINKED ISSUE #2: Adjust links in README.md
## Acceptance criteria

- [ ] The README.md file is updated with links as specified in the instructions.

## Details

See the README.md file in the repo for details.

### PR DESCRIPTION
**Pull request by erica-ll**
Edited README.md with team's information and links to repo/deployment.

Closes #2

### CODE REVIEW

**Review by Garrett-Hu — CHANGES_REQUESTED** [review]
Line 16 doesn't need the .git. Line 18 I think we only need our deployment at dokku07.

**Review by YicongYan — APPROVED** [review]
Everything looks good to me!

**Review by Garrett-Hu — APPROVED** [review]
lgtm

**Review by bella-ward — APPROVED** [review]
Code looks good LGTM

**Pull request merged**
